### ISSUE TITLE
Glyphicons Missing

### ISSUE THREAD

**Issue by paulstefanort** [lucatironi/flatstrap-sass#1]
It seems that glyphicons are missing from flatstrap-sass. Whenever I try to use `<i class="icon-{type}"></i>`, I the generic unsupported character (rectangle) instead of the desired glyph.

**Comment by lucatironi** [comment]
Thanks for the input. I will push a new version very soon.

**Comment by codegrean** [comment]
I also got this problem. But it work after I install font-awesome-rails.

**Comment by lucatironi** [comment]
Sorry for the delay, but I got busy and overlooked this issue.

Anyway, the problem is that I used font-awesome-rails as a dependency to include the glyphicons but I forgot to add the info in the documentation needed in order to use it with flatstrap!

You just need to add the font-awesome-rails gem in the gem file and include the css in the application css manifest. I've updated the documentation in the readme.

Since flatstrap is upgrading to the latest version of bootstrap, I will soon release an update too. Keep tuned in.
